// solid/form/src/ui/FormItem.tsx
/** @jsxImportSource solid-js */
import type { JSX } from 'solid-js';
import { Show, children as solidChildren, splitProps } from 'solid-js'
import { useValidator } from '../core/useValidator'
import type { NamePath, Rule, FormInstance } from '../core/type'
import { useField } from '../core'
import { useFormContext } from '../core/context'

export interface FormItemProps<T extends unknown = unknown>
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'children'> {
  label?: string
  noStyle?: boolean

  children: (params: { value: T; onChange: (val: T) => void }) => JSX.Element
  name: NamePath
  rules?: Rule[]
  dataTestid?: string
  formInstance?: FormInstance
}

export function FormItem<T>(props: FormItemProps<T>) {
  const [local, rest] = splitProps(props, [
    'children',
    'name',
    'rules',
    'label',
    'noStyle',
    'dataTestid',
    'formInstance',
  ])

  const contextFormInstance = useFormContext()

  const finalFormInstance = local.formInstance || contextFormInstance

  const { value, onChange } = useField<T>(local.name, { formInstance: finalFormInstance })

  const { message, methods } = useValidator(local.name, {
    rules: local.rules,
    label: local.label,
    formInstance: finalFormInstance,
  })

  const handChange = (val: any) => {
    onChange(val)
    methods?.onChange?.()
  }

  // 解析子组件
  const resolvedChildren = solidChildren(() => {
    if (typeof local.children === 'function') {
      return local.children({ value: value() as T, onChange: handChange })
    }
    return local.children
  })

  // 如果是无样式模式，直接返回子组件
  if (local.noStyle) {
    return resolvedChildren()
  }

  // 带样式的表单项
  return (
    <div data-testid={local.dataTestid} {...rest}>
      <Show when={local.label}>
        <label>{local.label}</label>
      </Show>
      {resolvedChildren()}
      <Show when={message()?.error}>
        <div data-testid={local.dataTestid ? `${local.dataTestid}-error` : undefined}>
          {message()?.error?.join('-')}
        </div>
      </Show>

      <Show when={message()?.warn}>
        <div data-testid={local.dataTestid ? `${local.dataTestid}-warn` : undefined}>
          {message()?.warn?.join('-')}
        </div>
      </Show>
    </div>
  )
}

// react/form/src/ui/FormItem.tsx
import type { ComponentProps, ReactElement } from 'react'
import type React from 'react'
import { isValidElement, memo, useCallback } from 'react'
import { useField, type NamePath, type Rule } from '../core'
import { useValidator } from '../core/useValidator'

export type FormItemProps<T extends React.ElementType> = {
  label?: string
  noStyle?: boolean
  style?: React.CSSProperties
  className?: string
  children: ReactElement<ComponentProps<T>>
  name: NamePath
  rules?: Rule[]
  dataTestid?: string
}

export function FormItemFc<T extends React.ElementType>(props: FormItemProps<T>) {
  const { noStyle = false, children, name, rules, dataTestid, label } = props
  const { value, onChange } = useField(name)

  const { message, methods } = useValidator(name, { rules, label })

  const handChange = useCallback((val: any) => {
    onChange(val)
    methods?.onChange?.()
    children.props.onChange?.(val)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  if (!isValidElement(children)) {
    return null
  }

  const Item = children.type
  const $children = <Item {...children.props} value={value} {...methods} onChange={handChange} />

  if (noStyle) {
    return $children
  }

  return (
    <div data-testid={dataTestid}>
      {label ? <label>{label}</label> : null}
      {$children}
      {message?.error ? (
        <div data-testid={dataTestid ? `${dataTestid}-error` : undefined}>
          {message.error.join('-')}
        </div>
      ) : null}
      {message?.warn ? (
        <div data-testid={dataTestid ? `${dataTestid}-warn` : undefined}>
          {message.warn.join('-')}
        </div>
      ) : null}
    </div>
  )
}

export const FormItem = memo(FormItemFc)
