// solid/solid/src/Provider.tsx
/** @jsxImportSource solid-js */
import { getDefaultStore, Store } from '@einfach/core'
import { createContext, useContext } from 'solid-js'
import { JSX } from 'solid-js/jsx-runtime'
import { StoreContextValue } from './type'

export const defaultStore = getDefaultStore()

// 创建 store context
export const StoreContext = createContext<StoreContextValue>({ store: defaultStore })

export interface ProviderProps {
  store?: Store
  children: JSX.Element
}

/**
 * Einfach Provider 组件
 * 提供自定义 store 的能力
 */
export function Provider(props: ProviderProps) {
  const { store = defaultStore, children } = props
  return <StoreContext.Provider value={{ store }}>{children}</StoreContext.Provider>
}

/**
 * 使用当前 store 的 hook
 */
export function useStoreContext(): StoreContextValue {
  return useContext(StoreContext)
}

// packages/react/src/Provider.tsx
import type { ReactNode } from 'react'
import { createContext } from 'react'
import type { Store } from '@einfach/core'

export const StoreContext = createContext<Store>(null as unknown as Store)

export function Provider({ store, children }: { store: Store; children: ReactNode }) {
  return <StoreContext.Provider value={store}>{children}</StoreContext.Provider>
}
