// solid/form/src/ui/Form.tsx
/** @jsxImportSource solid-js */

import { FormContext } from '../core/context'
import type { JSX } from 'solid-js'
import type { FormInstance } from '../core/type'

interface FormProps {
  children: JSX.Element
  formInstance: FormInstance
}

export function Form(props: FormProps) {
  return <FormContext.Provider value={props.formInstance}>{props.children}</FormContext.Provider>
}

// packages/form/src/Form.tsx
import React from 'react'
import { FormContext } from './content'
import type { FormInstance } from './type'

export function Form({
  children,
  formInstance,
}: {
  children: React.ReactNode
  formInstance: FormInstance
}) {
  return <FormContext.Provider value={formInstance}>{children}</FormContext.Provider>
}
